version: "3.8"
services:
  fastapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  

  quasar:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Local port : Container port

