version: "3.8"
services:
  fastapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8  # Google Public DNS
      - 8.8.4.4  # Google Public DNS (secondary)  # Local port : Container port

  quasar:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Local port : Container port

